# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager-low.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cartesi_base_pb2 as cartesi__base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='manager-low.proto',
  package='CartesiManagerLow',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11manager-low.proto\x12\x11\x43\x61rtesiManagerLow\x1a\x12\x63\x61rtesi-base.proto\"5\n\x0e\x41\x64\x64ressRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t2a\n\x11MachineManagerLow\x12L\n\x12\x43ommunicateAddress\x12!.CartesiManagerLow.AddressRequest\x1a\x11.CartesiCore.Void\"\x00\x62\x06proto3')
  ,
  dependencies=[cartesi__base__pb2.DESCRIPTOR,])




_ADDRESSREQUEST = _descriptor.Descriptor(
  name='AddressRequest',
  full_name='CartesiManagerLow.AddressRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='CartesiManagerLow.AddressRequest.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='CartesiManagerLow.AddressRequest.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['AddressRequest'] = _ADDRESSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddressRequest = _reflection.GeneratedProtocolMessageType('AddressRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSREQUEST,
  __module__ = 'manager_low_pb2'
  # @@protoc_insertion_point(class_scope:CartesiManagerLow.AddressRequest)
  ))
_sym_db.RegisterMessage(AddressRequest)



_MACHINEMANAGERLOW = _descriptor.ServiceDescriptor(
  name='MachineManagerLow',
  full_name='CartesiManagerLow.MachineManagerLow',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=115,
  serialized_end=212,
  methods=[
  _descriptor.MethodDescriptor(
    name='CommunicateAddress',
    full_name='CartesiManagerLow.MachineManagerLow.CommunicateAddress',
    index=0,
    containing_service=None,
    input_type=_ADDRESSREQUEST,
    output_type=cartesi__base__pb2._VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MACHINEMANAGERLOW)

DESCRIPTOR.services_by_name['MachineManagerLow'] = _MACHINEMANAGERLOW

# @@protoc_insertion_point(module_scope)
