# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cartesi_base_pb2 as cartesi__base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='manager.proto',
  package='CartesiManager',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmanager.proto\x12\x0e\x43\x61rtesiManager\x1a\x12\x63\x61rtesi-base.proto\"U\n\x11NewSessionRequest\x12,\n\x07machine\x18\x01 \x01(\x0b\x32\x1b.CartesiCore.MachineRequest\x12\x12\n\nsession_id\x18\x02 \x01(\t\"\x1b\n\x0bMachineHash\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\"6\n\x11SessionRunRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\r\n\x05times\x18\x02 \x03(\x04\"p\n\x10\x45xecutionSummary\x12)\n\x07summary\x18\x01 \x01(\x0b\x32\x18.CartesiCore.RunResponse\x12\x31\n\x0cmachine_hash\x18\x02 \x01(\x0b\x32\x1b.CartesiManager.MachineHash\"J\n\x12SessionRunResponse\x12\x34\n\nexecutions\x18\x01 \x03(\x0b\x32 .CartesiManager.ExecutionSummary\"6\n\x12SessionStepRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x04\":\n\x13SessionStepResponse\x12#\n\x03log\x18\x01 \x01(\x0b\x32\x16.CartesiCore.AccessLog\"\x1a\n\nUnixSocket\x12\x0c\n\x04path\x18\x01 \x01(\t\"\'\n\tTCPSocket\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\"}\n\x10ReferenceRequest\x12*\n\x04unix\x18\x01 \x01(\x0b\x32\x1a.CartesiManager.UnixSocketH\x00\x12(\n\x03tcp\x18\x02 \x01(\x0b\x32\x19.CartesiManager.TCPSocketH\x00\x42\x13\n\x11socket_type_oneof2\xe0\x02\n\x0eMachineManager\x12N\n\nNewSession\x12!.CartesiManager.NewSessionRequest\x1a\x1b.CartesiManager.MachineHash\"\x00\x12U\n\nSessionRun\x12!.CartesiManager.SessionRunRequest\x1a\".CartesiManager.SessionRunResponse\"\x00\x12X\n\x0bSessionStep\x12\".CartesiManager.SessionStepRequest\x1a#.CartesiManager.SessionStepResponse\"\x00\x12M\n\x14\x43ommunicateReference\x12 .CartesiManager.ReferenceRequest\x1a\x11.CartesiCore.Void\"\x00\x62\x06proto3')
  ,
  dependencies=[cartesi__base__pb2.DESCRIPTOR,])




_NEWSESSIONREQUEST = _descriptor.Descriptor(
  name='NewSessionRequest',
  full_name='CartesiManager.NewSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='machine', full_name='CartesiManager.NewSessionRequest.machine', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='CartesiManager.NewSessionRequest.session_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=138,
)


_MACHINEHASH = _descriptor.Descriptor(
  name='MachineHash',
  full_name='CartesiManager.MachineHash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='CartesiManager.MachineHash.hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=167,
)


_SESSIONRUNREQUEST = _descriptor.Descriptor(
  name='SessionRunRequest',
  full_name='CartesiManager.SessionRunRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='CartesiManager.SessionRunRequest.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='times', full_name='CartesiManager.SessionRunRequest.times', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=223,
)


_EXECUTIONSUMMARY = _descriptor.Descriptor(
  name='ExecutionSummary',
  full_name='CartesiManager.ExecutionSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='summary', full_name='CartesiManager.ExecutionSummary.summary', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='machine_hash', full_name='CartesiManager.ExecutionSummary.machine_hash', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=337,
)


_SESSIONRUNRESPONSE = _descriptor.Descriptor(
  name='SessionRunResponse',
  full_name='CartesiManager.SessionRunResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='executions', full_name='CartesiManager.SessionRunResponse.executions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=413,
)


_SESSIONSTEPREQUEST = _descriptor.Descriptor(
  name='SessionStepRequest',
  full_name='CartesiManager.SessionStepRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='CartesiManager.SessionStepRequest.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='CartesiManager.SessionStepRequest.time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=469,
)


_SESSIONSTEPRESPONSE = _descriptor.Descriptor(
  name='SessionStepResponse',
  full_name='CartesiManager.SessionStepResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log', full_name='CartesiManager.SessionStepResponse.log', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=529,
)


_UNIXSOCKET = _descriptor.Descriptor(
  name='UnixSocket',
  full_name='CartesiManager.UnixSocket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='CartesiManager.UnixSocket.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=531,
  serialized_end=557,
)


_TCPSOCKET = _descriptor.Descriptor(
  name='TCPSocket',
  full_name='CartesiManager.TCPSocket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='CartesiManager.TCPSocket.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='CartesiManager.TCPSocket.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=559,
  serialized_end=598,
)


_REFERENCEREQUEST = _descriptor.Descriptor(
  name='ReferenceRequest',
  full_name='CartesiManager.ReferenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unix', full_name='CartesiManager.ReferenceRequest.unix', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tcp', full_name='CartesiManager.ReferenceRequest.tcp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='socket_type_oneof', full_name='CartesiManager.ReferenceRequest.socket_type_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=600,
  serialized_end=725,
)

_NEWSESSIONREQUEST.fields_by_name['machine'].message_type = cartesi__base__pb2._MACHINEREQUEST
_EXECUTIONSUMMARY.fields_by_name['summary'].message_type = cartesi__base__pb2._RUNRESPONSE
_EXECUTIONSUMMARY.fields_by_name['machine_hash'].message_type = _MACHINEHASH
_SESSIONRUNRESPONSE.fields_by_name['executions'].message_type = _EXECUTIONSUMMARY
_SESSIONSTEPRESPONSE.fields_by_name['log'].message_type = cartesi__base__pb2._ACCESSLOG
_REFERENCEREQUEST.fields_by_name['unix'].message_type = _UNIXSOCKET
_REFERENCEREQUEST.fields_by_name['tcp'].message_type = _TCPSOCKET
_REFERENCEREQUEST.oneofs_by_name['socket_type_oneof'].fields.append(
  _REFERENCEREQUEST.fields_by_name['unix'])
_REFERENCEREQUEST.fields_by_name['unix'].containing_oneof = _REFERENCEREQUEST.oneofs_by_name['socket_type_oneof']
_REFERENCEREQUEST.oneofs_by_name['socket_type_oneof'].fields.append(
  _REFERENCEREQUEST.fields_by_name['tcp'])
_REFERENCEREQUEST.fields_by_name['tcp'].containing_oneof = _REFERENCEREQUEST.oneofs_by_name['socket_type_oneof']
DESCRIPTOR.message_types_by_name['NewSessionRequest'] = _NEWSESSIONREQUEST
DESCRIPTOR.message_types_by_name['MachineHash'] = _MACHINEHASH
DESCRIPTOR.message_types_by_name['SessionRunRequest'] = _SESSIONRUNREQUEST
DESCRIPTOR.message_types_by_name['ExecutionSummary'] = _EXECUTIONSUMMARY
DESCRIPTOR.message_types_by_name['SessionRunResponse'] = _SESSIONRUNRESPONSE
DESCRIPTOR.message_types_by_name['SessionStepRequest'] = _SESSIONSTEPREQUEST
DESCRIPTOR.message_types_by_name['SessionStepResponse'] = _SESSIONSTEPRESPONSE
DESCRIPTOR.message_types_by_name['UnixSocket'] = _UNIXSOCKET
DESCRIPTOR.message_types_by_name['TCPSocket'] = _TCPSOCKET
DESCRIPTOR.message_types_by_name['ReferenceRequest'] = _REFERENCEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewSessionRequest = _reflection.GeneratedProtocolMessageType('NewSessionRequest', (_message.Message,), dict(
  DESCRIPTOR = _NEWSESSIONREQUEST,
  __module__ = 'manager_pb2'
  # @@protoc_insertion_point(class_scope:CartesiManager.NewSessionRequest)
  ))
_sym_db.RegisterMessage(NewSessionRequest)

MachineHash = _reflection.GeneratedProtocolMessageType('MachineHash', (_message.Message,), dict(
  DESCRIPTOR = _MACHINEHASH,
  __module__ = 'manager_pb2'
  # @@protoc_insertion_point(class_scope:CartesiManager.MachineHash)
  ))
_sym_db.RegisterMessage(MachineHash)

SessionRunRequest = _reflection.GeneratedProtocolMessageType('SessionRunRequest', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONRUNREQUEST,
  __module__ = 'manager_pb2'
  # @@protoc_insertion_point(class_scope:CartesiManager.SessionRunRequest)
  ))
_sym_db.RegisterMessage(SessionRunRequest)

ExecutionSummary = _reflection.GeneratedProtocolMessageType('ExecutionSummary', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTIONSUMMARY,
  __module__ = 'manager_pb2'
  # @@protoc_insertion_point(class_scope:CartesiManager.ExecutionSummary)
  ))
_sym_db.RegisterMessage(ExecutionSummary)

SessionRunResponse = _reflection.GeneratedProtocolMessageType('SessionRunResponse', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONRUNRESPONSE,
  __module__ = 'manager_pb2'
  # @@protoc_insertion_point(class_scope:CartesiManager.SessionRunResponse)
  ))
_sym_db.RegisterMessage(SessionRunResponse)

SessionStepRequest = _reflection.GeneratedProtocolMessageType('SessionStepRequest', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONSTEPREQUEST,
  __module__ = 'manager_pb2'
  # @@protoc_insertion_point(class_scope:CartesiManager.SessionStepRequest)
  ))
_sym_db.RegisterMessage(SessionStepRequest)

SessionStepResponse = _reflection.GeneratedProtocolMessageType('SessionStepResponse', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONSTEPRESPONSE,
  __module__ = 'manager_pb2'
  # @@protoc_insertion_point(class_scope:CartesiManager.SessionStepResponse)
  ))
_sym_db.RegisterMessage(SessionStepResponse)

UnixSocket = _reflection.GeneratedProtocolMessageType('UnixSocket', (_message.Message,), dict(
  DESCRIPTOR = _UNIXSOCKET,
  __module__ = 'manager_pb2'
  # @@protoc_insertion_point(class_scope:CartesiManager.UnixSocket)
  ))
_sym_db.RegisterMessage(UnixSocket)

TCPSocket = _reflection.GeneratedProtocolMessageType('TCPSocket', (_message.Message,), dict(
  DESCRIPTOR = _TCPSOCKET,
  __module__ = 'manager_pb2'
  # @@protoc_insertion_point(class_scope:CartesiManager.TCPSocket)
  ))
_sym_db.RegisterMessage(TCPSocket)

ReferenceRequest = _reflection.GeneratedProtocolMessageType('ReferenceRequest', (_message.Message,), dict(
  DESCRIPTOR = _REFERENCEREQUEST,
  __module__ = 'manager_pb2'
  # @@protoc_insertion_point(class_scope:CartesiManager.ReferenceRequest)
  ))
_sym_db.RegisterMessage(ReferenceRequest)



_MACHINEMANAGER = _descriptor.ServiceDescriptor(
  name='MachineManager',
  full_name='CartesiManager.MachineManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=728,
  serialized_end=1080,
  methods=[
  _descriptor.MethodDescriptor(
    name='NewSession',
    full_name='CartesiManager.MachineManager.NewSession',
    index=0,
    containing_service=None,
    input_type=_NEWSESSIONREQUEST,
    output_type=_MACHINEHASH,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SessionRun',
    full_name='CartesiManager.MachineManager.SessionRun',
    index=1,
    containing_service=None,
    input_type=_SESSIONRUNREQUEST,
    output_type=_SESSIONRUNRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SessionStep',
    full_name='CartesiManager.MachineManager.SessionStep',
    index=2,
    containing_service=None,
    input_type=_SESSIONSTEPREQUEST,
    output_type=_SESSIONSTEPRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CommunicateReference',
    full_name='CartesiManager.MachineManager.CommunicateReference',
    index=3,
    containing_service=None,
    input_type=_REFERENCEREQUEST,
    output_type=cartesi__base__pb2._VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MACHINEMANAGER)

DESCRIPTOR.services_by_name['MachineManager'] = _MACHINEMANAGER

# @@protoc_insertion_point(module_scope)
