// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: manager-low.proto

#include "manager-low.pb.h"
#include "manager-low.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace CartesiManagerLow {

static const char* MachineManagerLow_method_names[] = {
  "/CartesiManagerLow.MachineManagerLow/CommunicateAddress",
};

std::unique_ptr< MachineManagerLow::Stub> MachineManagerLow::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MachineManagerLow::Stub> stub(new MachineManagerLow::Stub(channel));
  return stub;
}

MachineManagerLow::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_CommunicateAddress_(MachineManagerLow_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MachineManagerLow::Stub::CommunicateAddress(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest& request, ::CartesiCore::Void* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CommunicateAddress_, context, request, response);
}

void MachineManagerLow::Stub::experimental_async::CommunicateAddress(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest* request, ::CartesiCore::Void* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CommunicateAddress_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::CartesiCore::Void>* MachineManagerLow::Stub::AsyncCommunicateAddressRaw(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::CartesiCore::Void>::Create(channel_.get(), cq, rpcmethod_CommunicateAddress_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::CartesiCore::Void>* MachineManagerLow::Stub::PrepareAsyncCommunicateAddressRaw(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::CartesiCore::Void>::Create(channel_.get(), cq, rpcmethod_CommunicateAddress_, context, request, false);
}

MachineManagerLow::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MachineManagerLow_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MachineManagerLow::Service, ::CartesiManagerLow::AddressRequest, ::CartesiCore::Void>(
          std::mem_fn(&MachineManagerLow::Service::CommunicateAddress), this)));
}

MachineManagerLow::Service::~Service() {
}

::grpc::Status MachineManagerLow::Service::CommunicateAddress(::grpc::ServerContext* context, const ::CartesiManagerLow::AddressRequest* request, ::CartesiCore::Void* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace CartesiManagerLow

