// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: manager-low.proto
#ifndef GRPC_manager_2dlow_2eproto__INCLUDED
#define GRPC_manager_2dlow_2eproto__INCLUDED

#include "manager-low.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace CartesiManagerLow {

class MachineManagerLow final {
 public:
  static constexpr char const* service_full_name() {
    return "CartesiManagerLow.MachineManagerLow";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CommunicateAddress(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest& request, ::CartesiCore::Void* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CartesiCore::Void>> AsyncCommunicateAddress(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CartesiCore::Void>>(AsyncCommunicateAddressRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CartesiCore::Void>> PrepareAsyncCommunicateAddress(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CartesiCore::Void>>(PrepareAsyncCommunicateAddressRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void CommunicateAddress(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest* request, ::CartesiCore::Void* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::CartesiCore::Void>* AsyncCommunicateAddressRaw(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::CartesiCore::Void>* PrepareAsyncCommunicateAddressRaw(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status CommunicateAddress(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest& request, ::CartesiCore::Void* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CartesiCore::Void>> AsyncCommunicateAddress(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CartesiCore::Void>>(AsyncCommunicateAddressRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CartesiCore::Void>> PrepareAsyncCommunicateAddress(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CartesiCore::Void>>(PrepareAsyncCommunicateAddressRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void CommunicateAddress(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest* request, ::CartesiCore::Void* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::CartesiCore::Void>* AsyncCommunicateAddressRaw(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::CartesiCore::Void>* PrepareAsyncCommunicateAddressRaw(::grpc::ClientContext* context, const ::CartesiManagerLow::AddressRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CommunicateAddress_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CommunicateAddress(::grpc::ServerContext* context, const ::CartesiManagerLow::AddressRequest* request, ::CartesiCore::Void* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CommunicateAddress : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_CommunicateAddress() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CommunicateAddress() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CommunicateAddress(::grpc::ServerContext* context, const ::CartesiManagerLow::AddressRequest* request, ::CartesiCore::Void* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCommunicateAddress(::grpc::ServerContext* context, ::CartesiManagerLow::AddressRequest* request, ::grpc::ServerAsyncResponseWriter< ::CartesiCore::Void>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CommunicateAddress<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_CommunicateAddress : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_CommunicateAddress() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CommunicateAddress() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CommunicateAddress(::grpc::ServerContext* context, const ::CartesiManagerLow::AddressRequest* request, ::CartesiCore::Void* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CommunicateAddress : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_CommunicateAddress() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CommunicateAddress() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CommunicateAddress(::grpc::ServerContext* context, const ::CartesiManagerLow::AddressRequest* request, ::CartesiCore::Void* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCommunicateAddress(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CommunicateAddress : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_CommunicateAddress() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::CartesiManagerLow::AddressRequest, ::CartesiCore::Void>(std::bind(&WithStreamedUnaryMethod_CommunicateAddress<BaseClass>::StreamedCommunicateAddress, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_CommunicateAddress() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CommunicateAddress(::grpc::ServerContext* context, const ::CartesiManagerLow::AddressRequest* request, ::CartesiCore::Void* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCommunicateAddress(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::CartesiManagerLow::AddressRequest,::CartesiCore::Void>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CommunicateAddress<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CommunicateAddress<Service > StreamedService;
};

}  // namespace CartesiManagerLow


#endif  // GRPC_manager_2dlow_2eproto__INCLUDED
