[package]
description = "Cartesi Transaction Manager"
homepage = "https://cartesi.io"
name = "emulator_interface"
version = "0.1.0"
authors = ["Cartesi Team"]

[dependencies]
protobuf = "2"
grpc = "~0.6"
protoc-rust-grpc = "0.6.1"

[[bin]]
name = "build-emulator-interface"
path = "src/build.rs"
